version: "3"

services:
  app:
    image: java:8
    ports:
      - "8083:8081"
    container_name: springboot_docker
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: account

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "8082:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: account

volumes:
  mysql-data: